# Generated by Django 5.0.1 on 2024-01-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('experience', models.TextField()),
                ('total_projects', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('salary', models.IntegerField()),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='posts/')),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('count_views', models.IntegerField(default=0)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('full_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='profile/')),
                ('bio', models.TextField()),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('order',),
            },
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('link', models.URLField()),
                ('complated_at', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category')),
                ('used_tools', models.ManyToManyField(to='app.skill')),
            ],
            bases=('app.basemodel',),
        ),
    ]
